#! /usr/bin/env ansible-playbook
# Configure systemd DNS resolver
# Replace 'all' with your own inventory group
---
- name: systemd-resolved | apply role
  hosts: all
  roles:
  - role: systemd-resolved
    tags:
    - resolved
    - dns
